name: Notify Checker
on:
    push:
        branches:
            - main
    workflow_dispatch:
    schedule:
        - cron: "*/10 * * * *"
    
jobs:
    Notify-Check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v4
              with:
                  python-version: '3.10' 
                  
            - name: Download Requrements and setup git
              env:
                USERNAME: ${{ secrets.USERNAME }}
                EMAIL: ${{ secrets.EMAIL }}
              run: |
                cd $GITHUB_WORKSPACE
                pip install -r requirements.txt
                git config --global user.name $USERNAME
                git config --global user.email $EMAIL
            
            - name: Run Program
              env:
                  BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
                  CHAT_ID: ${{ secrets.CHAT_ID }}
                  BASE_URL: ${{ secrets.BASE_URL }}
              run: |
                cd $GITHUB_WORKSPACE
                python3 main.py
                git push